# Generated by Django 5.2.6 on 2025-09-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='A_name',
        ),
    ]
